### PR TITLE
Add option to disable writing headers

### PR DESCRIPTION
**Pull request by cljoly**
This option prevents metrics from being written in the corresponding
header of the response.

This is useful to collect the metrics all the time but have a setting to
actually write it in the answer. For instance, this is desirable for
https://github.com/miniflux/miniflux/pull/806/

### CODE REVIEW

**Comment by cljoly** [comment]
@mitchellh ping (in case the notification got lost) :-)

**Review by mitchellh — APPROVED** [review]
Looks great. Thanks! Sorry I did lose this in my inbox.

**Comment by cljoly** [comment]
Awesome, thanks!

**Comment by cljoly** [comment]
@mitchellh could you please consider tagging a commit with this functionality to ease use in other projects?

**Pull request merged**
